on:
  release:
    types: [created]

name: Create release artifact

jobs:
  build:
    name: Create release artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Install composer dependencies
        run: |
          cd wp-content/plugins/shared-uploads-directory-wp
          composer install

      - name: ZIP
        run: |
          mkdir shared-uploads-directory-wp
          cp -R ./wp-content/plugins/shared-uploads-directory-wp/* ./shared-uploads-directory-wp
          zip -r shared-uploads-directory-wp.zip shared-uploads-directory-wp

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: shared-uploads-directory-wp.zip
          asset_path: ./shared-uploads-directory-wp.zip
          asset_content_type: application/zip
